### ISSUE TITLE
"Hero" and "Short Bios" images distorted or not showing up in Apple ipad

### ISSUE THREAD

**Issue by cosola** [cosola-salvia/news.macile.org#62]
- Investigate why hero image shows distorted in Apple ipad and smaller devices; adjust and test.
- Increase hero text for small devices to improve visibility.
- Short Bios pictures not showing in Apple ipad

**Comment by Morban15** [comment]
Maybe

```
<img class="post-albums__scholar--photo" src=/"app/assets/images/nicolepinales2.png" itemprop="image">
```
could be making the *Short Bios*'s problem.
(The `src`. I repared it into the `publicationDate` branch)

**Comment by misscs** [comment]
How are you testing iPad? Are you using the browsers iPad setting?

**Comment by Morban15** [comment]
Can I do that with Windows?

**Comment by Morban15** [comment]
Now it works. After fix the `src`

![shortBios](https://user-images.githubusercontent.com/29107510/78807497-2881c200-7992-11ea-9062-3e2ebafb5a79.png)

![shortBios1](https://user-images.githubusercontent.com/29107510/78807516-2f103980-7992-11ea-995e-0e48981b447f.png)

**Comment by Morban15** [comment]
Also, the problem with the *home-hero picture* could be that the url is relative in css file?

![homeHeroPic](https://user-images.githubusercontent.com/29107510/78838118-77941b00-79c3-11ea-94f8-7e471f831d90.png)

I changed it when I was updating the paths, but I couldn't test it.

**Comment by Morban15** [comment]
No, ese no es el problema con *home-hero*

**Comment by Morban15** [comment]
Según https://stackoverflow.com/questions/38083150/background-image-blurry-on-mobile-ios
el problema es con `background-attachment: fixed;`. Lo removí y luego lo probé. Funciona

![homeHeroFixed](https://user-images.githubusercontent.com/29107510/79150411-bd236000-7d96-11ea-80ae-ac0ef720ad1e.png)
