### ISSUE TITLE
Verify why an extra margin-right appears in the newsletter and bulletin, and fix it.

### ISSUE THREAD

**Issue by Morban15** [cosola-salvia/news.macile.org#86]
### `dev` branch

![dev-problem](https://user-images.githubusercontent.com/29107510/79606550-c75b9c00-80bf-11ea-9b20-427db7e35584.png)

### `release-bulletin-v1` branch

![bulletin-problem](https://user-images.githubusercontent.com/29107510/79606593-d5a9b800-80bf-11ea-9a44-5aeb5009b833.png)

**Comment by misscs** [comment]
This is a good story to tackle if you find yourself without things to do.
